# -*- coding: utf-8 -*-
"""Chloropleth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gx3P-5PX1foEfsNHSiImpe6zyd04C89o
"""

import os
from google.colab import drive
drive.mount('/content/drive')

lokasi_file = "/content/drive/MyDrive/PROJECT"
os.chdir(lokasi_file)

print("directory: ", os.getcwd())

import geopandas as gpd

kota_bekasi = gpd.read_file("kota_bekasi.geojson")
landuse_bekasi = gpd.read_file("landuse_bekasi.geojson")
cafe_bekasi = gpd.read_file("cafe_bekasi.geojson")

# wgs84 to utm 48s
kota_bekasi_utm = kota_bekasi.to_crs(epsg=32748)
landuse_bekasi_utm = landuse_bekasi.to_crs(epsg=32748)
cafe_bekasi_utm = cafe_bekasi.to_crs(epsg=32748)

kota_bekasi_utm
kota_bekasi_utm.plot()

import matplotlib.pyplot as plt

fig = plt.figure(figsize=(8,6))
fig, ax = plt.subplots(figsize=(8,6))
kota_bekasi_utm.plot(ax=ax, edgecolor='white', facecolor='red')
ax.set_title("Peta Administrasi Kota Bekasi")
plt.show()

fig, ax = plt.subplots(figsize=(8,6))
landuse_bekasi.plot(ax=ax, edgecolor='white', facecolor='blue')
ax.set_title("Peta Persebaran Penggunaan Lahan Kota Bekasi")
plt.show()

# fig, ax = plt.subplots(figsize=(10,10))
# jalan_bekasi.plot(ax=ax, edgecolor='white', facecolor='black')
# ax.set_title("Peta Jaringan Jalan Kota Bekasi")
# plt.show()

fig,ax = plt.subplots(figsize=(8,8))

cafe_bekasi_utm.plot(ax=ax, edgecolor='white', facecolor='green')
ax.set_title("Peta Persebaran Cafe Kota Bekasi")
plt.show()

fig,ax = plt.subplots(1, 2, figsize=(8,8))

kota_bekasi_utm.plot(ax=ax[0], edgecolor='white', facecolor='red')
cafe_bekasi_utm.plot(ax=ax[1], edgecolor='white', facecolor='green')
ax[0].set_title("Peta Administrasi Kota Bekasi")
ax[1].set_title("Peta Cafe Kota Bekasi")
fig.suptitle("Peta Kota Bekasi")
plt.show()

fig, ax = plt.subplots(figsize=(8,6))

kota_bekasi_utm.plot(ax=ax, edgecolor='white', facecolor='red')
cafe_bekasi_utm.plot(ax=ax, edgecolor='black', facecolor='blue')
ax.set_title("Peta Persebaran Cafe Kota Bekasi")
plt.show()

fig,ax = plt.subplots(1,2, figsize=(8,8))

kota_bekasi_utm.plot(ax=ax[0], edgecolor='white', facecolor='red')
ax[0].set_title("Peta Administrasi Kota Bekasi")

kota_bekasi_utm.plot(ax=ax[1], edgecolor='white', facecolor='red')
landuse_bekasi_utm.plot(ax=ax[1], edgecolor='white', facecolor='blue')
ax[1].set_title("Peta Penggunaan Lahan Kota Bekasi")
plt.show()

kota_bekasi_utm.plot(ax=ax[1], edgecolor='white', facecolor='red')
cafe_bekasi_utm.plot(ax=ax[1], edgecolor='white', facecolor='green')
ax[1].set_title("Peta Cafe Kota Bekasi")
plt.show()

!pip install contextily
import contextily as cx

fig, ax = plt.subplots(1, 1, figsize=(6,6))
landuse_bekasi_utm.to_crs('epsg:3857').plot(ax=ax, edgecolor=None, facecolor='cyan')
cx.add_basemap(ax=ax)
plt.show()

populasi_bekasi = gpd.read_file("populasi_bekasi.geojson")

populasi_bekasi.plot(figsize=(10,10))

populasi_bekasi.head()

fig, ax = plt.subplots(figsize=(8,6))

populasi_bekasi.plot(column='Populasi', ax=ax, legend=True, cmap='Wistia')
ax.set_title("Peta Chloropleth Penduduk Kota Bekasi")

plt.show()

fig, ax = plt.subplots(figsize=(8,6))
populasi_bekasi.plot(column='Populasi', ax=ax, legend=True, cmap='Wistia', edgecolor='White', linewidth=1)

ax.set_title("Peta Populasi Penduduk di Kota Bekasi", fontsize=10)
ax.set_xlabel('Longitude', fontsize=5)
ax.set_ylabel('Latitude', fontsize=5)
plt.show()

from google.colab import output
output.enable_custom_widget_manager()

!pip install leafmap
import leafmap

koordinat = (-6.260458, 106.981281)
map = leafmap.Map(center=koordinat, zoom=14)
map

map.add_gdf(populasi_bekasi, layer_name='Peta Populasi Kota Bekasi', column="Populasi", scheme='cool')
map

map.to_html('map.html')

!pip install mapclassify

"""Support for third party widgets will remain active for the duration of the session. To disable support:"""

from google.colab import output
output.enable_custom_widget_manager()

!pip install mapclassify

import leafmap.foliumap as folium_map_module
import geopandas as gpd


populasi_bekasi['Populasi'] = populasi_bekasi['Populasi'].fillna(0).astype(float)
populasi_bekasi = populasi_bekasi.rename(columns={'WADMKC': 'Nama Kecamatan'})
populasi_bekasi = populasi_bekasi.rename(columns={'WADMKK': 'Nama Kota'})
populasi_bekasi = populasi_bekasi.rename(columns={'WADMPR': 'Provinsi'})


populasi_bekasi_wgs = populasi_bekasi.to_crs('EPSG:4326')

bounds = populasi_bekasi_wgs.total_bounds
center = [(bounds[1] + bounds[3]) / 2, (bounds[0] + bounds[2]) / 2]

map = folium_map_module.Map(center=center, zoom=10)

map.add_data(
    populasi_bekasi_wgs,
    column="Populasi",
    scheme="Quantiles",
    cmap="cool",
    legend_title="Populasi Penduduk Kota Bekasi Tahun 2024",
    layer_name="Kota Bekasi"
)

map